# Generated by Django 5.1.4 on 2024-12-21 04:06

import core.getCurrentUser
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('actor', '0001_initial'),
        ('shipments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Costing',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('costing_number', models.CharField(max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=10, max_digits=50)),
                ('paid_amount', models.DecimalField(decimal_places=10, max_digits=50)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('authorized', 'Authorized'), ('captured', 'Captured'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], max_length=20)),
                ('costing_status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('sent', 'Sent'), ('due', 'Due'), ('overdue', 'Overdue'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('processing', 'Processing'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], max_length=20)),
                ('created_date_editable', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='costings', to='accounting.currency')),
                ('shipment_job', models.ManyToManyField(blank=True, related_name='costings', to='shipments.shipment')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipment_costing_user', to=settings.AUTH_USER_MODEL)),
                ('user_add', models.ForeignKey(default=core.getCurrentUser.get_current_user, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='costings', to='actor.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bill_no', models.CharField(max_length=50, unique=True)),
                ('expense_cat', models.CharField(max_length=120)),
                ('exchange_rate_to_npr', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit'), ('purchase', 'Purchase'), ('e', 'Expense')], max_length=20)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True)),
                ('non_taxable_total', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True)),
                ('taxable_total', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True)),
                ('vat', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True)),
                ('grand_total', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('bank_accounts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='accounting.bankaccounts')),
                ('chart_of_accounts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='accounting.chartofaccounts')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='accounting.currency')),
                ('user_add', models.ForeignKey(default=core.getCurrentUser.get_current_user, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotesItem',
            fields=[
                ('id', models.BigAutoField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qty', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_type', models.CharField(choices=[('amount', 'Amount'), ('percent', 'Percent')], max_length=20)),
                ('tax_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase.expense')),
                ('user_add', models.ForeignKey(default=core.getCurrentUser.get_current_user, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VendorCreditDebitNote',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('note_number', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=10, max_digits=50)),
                ('reason', models.TextField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_credit_note', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_credit_debit_notes', to='accounting.currency')),
                ('user_add', models.ForeignKey(default=core.getCurrentUser.get_current_user, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_credit_debit_notes', to='actor.vendor')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='VendorPayment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=10, max_digits=50)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('authorized', 'Authorized'), ('captured', 'Captured'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], max_length=20)),
                ('payment_date', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('bank_accounts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_payments', to='accounting.bankaccounts')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_payments', to='accounting.currency')),
                ('shipment_job', models.ManyToManyField(blank=True, related_name='vendor_payments', to='purchase.costing')),
                ('user_add', models.ForeignKey(default=core.getCurrentUser.get_current_user, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_payments', to='actor.vendor')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
    ]
