# Generated by Django 5.1.4 on 2025-01-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_alter_historicalshipment_customs_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalshipment',
            name='complementary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shipment',
            name='complementary',
            field=models.BooleanField(default=False),
        ),
    ]
