# Generated by Django 5.1.4 on 2025-01-05 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0003_historicalshipment_complementary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltransit',
            name='transportation_type',
        ),
        migrations.RemoveField(
            model_name='transit',
            name='transportation_type',
        ),
    ]
