# Generated by Django 5.1.4 on 2025-01-06 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0005_alter_historicalshipment_customs_value_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalshipment',
            old_name='doc_ref_type',
            new_name='doc_ref_no',
        ),
        migrations.RenameField(
            model_name='shipment',
            old_name='doc_ref_type',
            new_name='doc_ref_no',
        ),
    ]
