# Generated by Django 5.1.4 on 2025-01-06 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0006_rename_doc_ref_type_historicalshipment_doc_ref_no_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalshipment',
            old_name='is_dangerous_good',
            new_name='is_dangerous_goods',
        ),
        migrations.RenameField(
            model_name='shipment',
            old_name='is_dangerous_good',
            new_name='is_dangerous_goods',
        ),
    ]
