# Generated by Django 5.1.4 on 2025-01-06 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0007_rename_is_dangerous_good_historicalshipment_is_dangerous_goods_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalshipment',
            old_name='packaing_list',
            new_name='packaging_list',
        ),
        migrations.RenameField(
            model_name='shipment',
            old_name='packaing_list',
            new_name='packaging_list',
        ),
    ]
