# Generated by Django 5.1.4 on 2025-01-09 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0008_rename_packaing_list_historicalshipment_packaging_list_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltransit',
            name='booking_status',
        ),
        migrations.RemoveField(
            model_name='historicaltransit',
            name='is_loaded',
        ),
        migrations.RemoveField(
            model_name='historicaltransit',
            name='master',
        ),
        migrations.RemoveField(
            model_name='transit',
            name='booking_status',
        ),
        migrations.RemoveField(
            model_name='transit',
            name='is_loaded',
        ),
        migrations.RemoveField(
            model_name='transit',
            name='master',
        ),
        migrations.AddField(
            model_name='historicalshipment',
            name='booking_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalshipment',
            name='is_loaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalshipment',
            name='master',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='shipments.shipment'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='booking_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='is_loaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shipment',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subshipments', to='shipments.shipment'),
        ),
    ]
