# Generated by Django 5.1.4 on 2025-01-09 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0009_remove_historicaltransit_booking_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltransit',
            name='type',
        ),
        migrations.RemoveField(
            model_name='transit',
            name='type',
        ),
    ]
