# Generated by Django 5.1.4 on 2025-01-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0010_remove_historicaltransit_type_remove_transit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalshipment',
            name='awb',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalshipment',
            name='bol',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalshipment',
            name='bol_land',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalshipment',
            name='cargo_terminal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalshipment',
            name='cargo_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalshipment',
            name='container_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalshipment',
            name='container_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalshipment',
            name='driver_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalshipment',
            name='flight_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalshipment',
            name='handling_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalshipment',
            name='handling_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalshipment',
            name='route',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalshipment',
            name='trailer_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalshipment',
            name='uld_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalshipment',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalshipment',
            name='vessel_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalshipment',
            name='voyage_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='awb',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='bol',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='bol_land',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='cargo_terminal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='cargo_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='container_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='container_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='driver_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='flight_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='handling_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='handling_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='route',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='trailer_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='uld_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='vessel_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='voyage_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
