# Generated by Django 5.1.4 on 2025-01-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0011_historicalshipment_awb_historicalshipment_bol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalshipment',
            name='destination_custom_clearance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalshipment',
            name='manifest_si_no',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='historicalshipment',
            name='open_financially',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalshipment',
            name='open_operationally',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalshipment',
            name='origin_custom_clearance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shipment',
            name='destination_custom_clearance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shipment',
            name='manifest_si_no',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='open_financially',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='open_operationally',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='origin_custom_clearance',
            field=models.BooleanField(default=False),
        ),
    ]
