# Generated by Django 5.1.4 on 2025-01-12 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0012_historicalshipment_destination_custom_clearance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalshipment',
            name='additionalInfo',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='additionalInfo',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
