# Generated by Django 5.1.4 on 2025-01-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0013_historicalshipment_additionalinfo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalshipment',
            name='additionalInfo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='additionalInfo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
