# Generated by Django 5.1.4 on 2024-12-26 04:38

import master.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch_id',
            field=models.CharField(blank=True, default=master.models.generate_custom_uuid, max_length=20, null=True, unique=True, verbose_name='Branch ID'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='incharges',
            field=models.ManyToManyField(blank=True, null=True, related_name='company_branch_head', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalbranch',
            name='branch_id',
            field=models.CharField(blank=True, db_index=True, default=master.models.generate_custom_uuid, max_length=20, null=True, verbose_name='Branch ID'),
        ),
    ]
