# Generated by Django 5.1.4 on 2024-12-26 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_alter_branch_branch_id_alter_branch_incharges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmasterdata',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masterdata',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
