# Generated by Django 5.1.4 on 2025-01-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_historicalmasterdata_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationsettings',
            name='PAN',
            field=models.CharField(blank=True, default='ABCPQ1234D', max_length=20, null=True, verbose_name='PAN'),
        ),
        migrations.AddField(
            model_name='applicationsettings',
            name='email',
            field=models.EmailField(blank=True, default='info@logisticscompany.com', max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='applicationsettings',
            name='phone',
            field=models.CharField(default='+1 800 555 1234', max_length=20, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='applicationsettings',
            name='accounting_details',
            field=models.TextField(default='Account type: Checking, Financial period: January - December'),
        ),
        migrations.AlterField(
            model_name='applicationsettings',
            name='address',
            field=models.TextField(default='123 Logistics Blvd, Suite 101, San Francisco, CA, 94101'),
        ),
        migrations.AlterField(
            model_name='applicationsettings',
            name='bank_details',
            field=models.TextField(default='Bank: XYZ Bank, Account: 123456789, Branch: San Francisco'),
        ),
        migrations.AlterField(
            model_name='applicationsettings',
            name='country',
            field=models.CharField(default='United States', max_length=100),
        ),
        migrations.AlterField(
            model_name='applicationsettings',
            name='financial_period_end',
            field=models.DateField(default='2025-12-31'),
        ),
        migrations.AlterField(
            model_name='applicationsettings',
            name='financial_period_start',
            field=models.DateField(default='2025-01-01'),
        ),
        migrations.AlterField(
            model_name='applicationsettings',
            name='logo',
            field=models.ImageField(default='logos/default_logo.png', upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='applicationsettings',
            name='name',
            field=models.CharField(default='My Logistics Company', max_length=255),
        ),
        migrations.AlterField(
            model_name='applicationsettings',
            name='state',
            field=models.CharField(blank=True, default='California', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shipmentprefixes',
            name='bill_prefix',
            field=models.CharField(blank=True, default='BILL', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shipmentprefixes',
            name='cash_transfer_prefix',
            field=models.CharField(blank=True, default='CT', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shipmentprefixes',
            name='cheque_prefix',
            field=models.CharField(blank=True, default='CHQ', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shipmentprefixes',
            name='credit_note_prefix',
            field=models.CharField(blank=True, default='CN', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shipmentprefixes',
            name='invoice_prefix',
            field=models.CharField(blank=True, default='INV', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shipmentprefixes',
            name='journal_voucher_prefix',
            field=models.CharField(blank=True, default='JV', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shipmentprefixes',
            name='packages_prefix',
            field=models.CharField(blank=True, default='PKG', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shipmentprefixes',
            name='shipment_prefix',
            field=models.CharField(blank=True, default='SHIP', max_length=20, null=True),
        ),
    ]
