# Generated by Django 5.1.4 on 2025-01-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_create_default_settings_and_prefixes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipmentprefixes',
            options={'verbose_name': 'Shipment Prefixes', 'verbose_name_plural': 'Shipment Prefixes'},
        ),
        migrations.AlterField(
            model_name='applicationsettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='shipmentprefixes',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
