# Generated by Django 5.1.4 on 2025-01-11 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_alter_shipmentprefixes_options_and_more'),
        ('master', '0007_create_default_settings_and_prefixes'),
    ]

    operations = [
    ]
