# Generated by Django 5.1.4 on 2025-01-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0009_create_default_settings_and_prefixes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationsettings',
            name='PAN',
            field=models.CharField(blank=True, default='ABCPQ1234D', max_length=200, null=True, verbose_name='PAN'),
        ),
    ]
