# Generated by Django 5.1.2 on 2024-12-20 08:23

import core.getCurrentUser
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalVendor',
            fields=[
                ('id', models.BigIntegerField(blank=True, db_index=True)),
                ('image', models.TextField(blank=True, max_length=100, null=True)),
                ('vendor_class', models.CharField(choices=[('Booking Agent', 'Booking Agent'), ('Carrier', 'Carrier'), ('Customer', 'Customer'), ('Customs Agent', 'Customs Agent'), ('Employee', 'Employee'), ('Vendor', 'Vendor')], max_length=20)),
                ('type', models.CharField(choices=[('individual', 'Individual'), ('company', 'Company')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('country_code', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('acc_no', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField()),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('no_of_days', models.IntegerField(default=0)),
                ('bank_info', models.TextField()),
                ('trn', models.CharField(blank=True, max_length=50, null=True)),
                ('iata', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('active', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('account_head', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.chartofaccounts')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_add', models.ForeignKey(blank=True, db_constraint=False, default=core.getCurrentUser.get_current_user, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='added_by_vendor')),
            ],
            options={
                'verbose_name': 'historical vendor',
                'verbose_name_plural': 'historical vendors',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vendor_images')),
                ('vendor_class', models.CharField(choices=[('Booking Agent', 'Booking Agent'), ('Carrier', 'Carrier'), ('Customer', 'Customer'), ('Customs Agent', 'Customs Agent'), ('Employee', 'Employee'), ('Vendor', 'Vendor')], max_length=20)),
                ('type', models.CharField(choices=[('individual', 'Individual'), ('company', 'Company')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('country_code', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('acc_no', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField()),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('no_of_days', models.IntegerField(default=0)),
                ('bank_info', models.TextField()),
                ('trn', models.CharField(blank=True, max_length=50, null=True)),
                ('iata', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('account_head', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.chartofaccounts')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendor_user', to=settings.AUTH_USER_MODEL)),
                ('user_add', models.ForeignKey(default=core.getCurrentUser.get_current_user, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='added_by_vendor')),
            ],
        ),
        migrations.CreateModel(
            name='BookingAgentVendor',
            fields=[
            ],
            options={
                'verbose_name': 'Booking Agent',
                'verbose_name_plural': 'Booking Agent',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('actor.vendor',),
        ),
        migrations.CreateModel(
            name='CarrierVendor',
            fields=[
            ],
            options={
                'verbose_name': 'Carrier',
                'verbose_name_plural': 'Carrier',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('actor.vendor',),
        ),
        migrations.CreateModel(
            name='CustomsAgentVendor',
            fields=[
            ],
            options={
                'verbose_name': 'Customs Agent',
                'verbose_name_plural': 'Customs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('actor.vendor',),
        ),
        migrations.CreateModel(
            name='VendorVendor',
            fields=[
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('actor.vendor',),
        ),
    ]
