# Generated by Django 5.1.4 on 2024-12-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookingAgentVendor',
        ),
        migrations.DeleteModel(
            name='CarrierVendor',
        ),
        migrations.DeleteModel(
            name='CustomsAgentVendor',
        ),
        migrations.DeleteModel(
            name='VendorVendor',
        ),
        migrations.AlterField(
            model_name='historicalvendor',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='historicalvendor',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalvendor',
            name='phone',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
