# Generated by Django 5.1.4 on 2024-12-25 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalpaymentmethod',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='paymentmethod',
            old_name='desc',
            new_name='description',
        ),
    ]
