# Generated by Django 5.1.2 on 2024-12-20 08:23

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('clients', '0001_initial'),
        ('shipments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalInvoice',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('invoice_number', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('sent', 'Sent'), ('due', 'Due'), ('overdue', 'Overdue'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('processing', 'Processing'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], max_length=20)),
                ('discount_amount', models.DecimalField(decimal_places=10, max_digits=50)),
                ('total_amount', models.DecimalField(decimal_places=10, max_digits=50)),
                ('paid_amount', models.DecimalField(decimal_places=10, max_digits=50)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('authorized', 'Authorized'), ('captured', 'Captured'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], max_length=20)),
                ('created_date_editable', models.DateField()),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('updated_date', models.DateField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('client', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clients.client')),
                ('currency', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.currency')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical invoice',
                'verbose_name_plural': 'historical invoices',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('sent', 'Sent'), ('due', 'Due'), ('overdue', 'Overdue'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('processing', 'Processing'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], max_length=20)),
                ('discount_amount', models.DecimalField(decimal_places=10, max_digits=50)),
                ('total_amount', models.DecimalField(decimal_places=10, max_digits=50)),
                ('paid_amount', models.DecimalField(decimal_places=10, max_digits=50)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('authorized', 'Authorized'), ('captured', 'Captured'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], max_length=20)),
                ('created_date_editable', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='clients.client')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='accounting.currency')),
                ('shipment_job', models.ManyToManyField(blank=True, to='shipments.shipment')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalCustomerPayments',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('amount', models.DecimalField(decimal_places=10, max_digits=50)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('authorized', 'Authorized'), ('captured', 'Captured'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], max_length=20)),
                ('payment_date', models.DateField()),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('bank_accounts', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.bankaccounts')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('payment_mode', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.paymentmethod')),
                ('invoice', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sales.invoice')),
            ],
            options={
                'verbose_name': 'historical customer payments',
                'verbose_name_plural': 'historical customer paymentss',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCreditNote',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('credit_note_number', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=10, max_digits=50)),
                ('reason', models.TextField()),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('client', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clients.client')),
                ('currency', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.currency')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sales.invoice')),
            ],
            options={
                'verbose_name': 'historical credit note',
                'verbose_name_plural': 'historical credit notes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='CustomerPayments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=10, max_digits=50)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('authorized', 'Authorized'), ('captured', 'Captured'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], max_length=20)),
                ('payment_date', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('bank_accounts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_payments', to='accounting.bankaccounts')),
                ('payment_mode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_payments', to='accounting.paymentmethod')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_payments', to='sales.invoice')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('credit_note_number', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=10, max_digits=50)),
                ('reason', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='clients.client')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='accounting.currency')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_notes', to='sales.invoice')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
