# Generated by Django 5.1.4 on 2025-01-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_historicalinvoice_status_alter_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoice',
            name='master_shipment_reference_no',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='master_shipment_reference_no',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
